### ISSUE TITLE
[BUG] Season: 2023, Round: 12, SS not correct time

### ISSUE THREAD

**Issue by cofievet** [theOehrly/Fast-F1#429] opened 2023-07-30 10:32 UTC
### Describe the issue:

Hi

The time for the sprint shootout is not correct. We haven't got the Q1 and Q2 time. And the Q3 time is set for the Q2
Can you check please 

Exemple for Max Verstappen : 
 Q1=NaT, Q2=Timedelta('0 days 00:01:49.056000'), Q3=NaT

Thanks

### Reproduce the code example:

```python
fastf1.get_session(2023, 12, 3)
```

**Comment by theOehrly** [comment] 2023-08-01 19:54
Please ensure you are using the most recent version of FastF1 (v3.0.7).

I don't have much time right now, so I can only look at this in one or two weeks, in case the problem persists. Sorry for that.

**Comment by theOehrly** [comment] 2023-08-21 21:32
I finally got around to looking into this. It isn't caused by an outdated version but actually by two separate bugs. It'll be fixed in the next release.

**Closed** 2023-08-29 07:41 UTC
Labels: bug
