### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nicZox** [theOehrly/Fast-F1#14] opened 2021-03-12 17:08 UTC
Hi, could you add some examples and more precise documentation on the livetiming module and how to extract the data, etc.?

**Comment by theOehrly** [comment] 2021-03-12 21:58
You usually only need to use one command:

`python -m fastf1.livetiming save outfile.txt`

This will save all data into 'outfile.txt'. Of course, you can use a different file name. 

The 'extract' option is only needed if you saved the data with the '--debug' argument. Debug mode basically skips the extracting steps and saves the raw data from the connection. Then you need to extract the actual data from that afterwards. Usually you don't need this.  

You still can't use the data after that currently because the api parser does not yet support it. I can only work on it since today as I had no data before that myself.
A new release with full support and better documentation is likely to come tomorrow. Bug are to be expected though as I have basically no time to test this.

**Comment by theOehrly** [comment] 2021-03-13 11:22
I noticed that I hadn't updated the documentation correctly for v2.1
That's now fixed. Live timing is also documented, including a usage example. 
Hopefully it's clear enough.
New release with full live timing functionality is out now

**Comment by nicZox** [comment] 2021-03-13 16:34
> You usually only need to use one command:
> 
> `python -m fastf1.livetiming save outfile.txt`
> 
> This will save all data into 'outfile.txt'. Of course, you can use a different file name.
> 
> The 'extract' option is only needed if you saved the data with the '--debug' argument. Debug mode basically skips the extracting steps and saves the raw data from the connection. Then you need to extract the actual data from that afterwards. Usually you don't need this.
> 
> You still can't use the data after that currently because the api parser does not yet support it. I can only work on it since today as I had no data before that myself.
> A new release with full support and better documentation is likely to come tomorrow. Bug are to be expected though as I have basically no time to test this.

Ok, I tried with today's session, but am I getting this error? Is it a Fast-F1 bug? For example the lack of an if?
I have copied / pasted the sample documentation

![image](https://user-images.githubusercontent.com/76594617/111036940-15893480-8422-11eb-868c-56886f722f25.png)

**Comment by Xwang1976** [comment] 2021-03-13 16:48
I've got the same error, but I've started saving data only this afternoon when the testing was already going on.
According to the documentation the recording must start before the beginning of the session and moreover  every 2 hours it is interrupted by the server.
So I would like to know:
1) is the above the cause of the error?
2) if so, for tomorrow in order to save data correctly should I start recording before early in the morning before the start?
3) the afternoon session is a different one or is the same of the morning (is the latter case I have to arrange a cron script that starts a new instance every one hour and 50 minutes from the morning till the end of the afternoon session and each instance must save on a different file. Is it correct?

**Comment by theOehrly** [comment] 2021-03-13 18:34
Your code is working, That was a bit of a dumb error on my side. Please update and it _should_ work then. I made a new release.


Regarding the questions:
> 
> 
> I've got the same error, but I've started saving data only this afternoon when the testing was already going on.
> According to the documentation the recording must start before the beginning of the session and moreover every 2 hours it is interrupted by the server.
> So I would like to know:
> 
>  1. is the above the cause of the error?

No, it was my fault. You still might have problems though if the data is incomplete. I really didn't have time to test this properly.

>  2. if so, for tomorrow in order to save data correctly should I start recording before early in the morning before the start?

Yes, if you start too early, my client may timeout. You can also increase the timeout. But I'm not sure if that works and how much earlier you can actually start. I started recording about three minutes before the session was scheduled to start. That worked when I tried it. 

>  3. the afternoon session is a different one or is the same of the morning (is the latter case I have to arrange a cron script that starts a new instance every one hour and 50 minutes from the morning till the end of the afternoon session and each instance must save on a different file. Is it correct?

I'm not really 100% sure on that. It's one session when loading timing data from the api. I think in general it's treated as one session. But I'm not sure if you can keep the recording going through the break.
Your cron script idea is correct. One recording starting every 1 hour and 50 minutes should work well. I did that for this afternoon session, only manually.
You may want to start before the morning session and then again three minutes before the afternoon session. And 1:50 intervals from then on. _Maybe_ the server will terminate the connection during the lunch break. I don't know yet.

**Comment by Xwang1976** [comment] 2021-03-13 23:29
Is it possible to run the command every hour.
I've understood that duplicate data are recgnized and deleted. Does it happen even if more than two files contain the same data?

**Comment by theOehrly** [comment] 2021-03-14 07:04
That's not explicitly tested but it should work in theory. It might be rather slow to load the data but that's more of a convenience problem I guess

**Comment by nicZox** [comment] 2021-03-14 15:31
> Is it possible to run the command every hour?
> I've understood that duplicated data are recognized and deleted. Does it happen even if more than two files contain the same data?

@Xwang1976 If you make the cron script, can you share it? Thanks

**Comment by Xwang1976** [comment] 2021-03-14 17:15
I've not made a cron job.
Instead I've created this script:

> #!/bin/bash
>  
>  _destinationFolder="/home/andreak/src/Python/F1data/livetiming/"
>  _fileName="livetiming"
>  _fileExt=".txt"
> _now=$(date +"%Y%m%d_%H%M%S")
> 
> cd $_destinationFolder
> python -m fastf1.livetiming save --timeout 600 $_fileName$_now$_fileExt

and I've called it using kalarm with a repetition every hour starting from 07:58.

This is the log file and as you can see all files had been interrupted after 2 hours (as expected) except for the last two one that exited because the session had stopped.
[F1livetiming.log](https://github.com/theOehrly/Fast-F1/files/6137139/F1livetiming.log)

Then I've tried to use to import the saved data using this python script:

> import fastf1
> from fastf1.livetiming.data import LiveTimingData
> 
> fastf1.Cache.enable_cache('/home/andreak/Documenti/FF1Data/')
> 
> livedata = LiveTimingData('/home/andreak/src/Python/F1data/livetiming/livetiming20210314_075800.txt','/home/andreak/src/Python/F1data/livetiming/livetiming20210314_085800.txt','/home/andreak/src/Python/F1data/livetiming/livetiming20210314_095800.txt','/home/andreak/src/Python/F1data/livetiming/livetiming20210314_105800.txt','/home/andreak/src/Python/F1data/livetiming/livetiming20210314_115800.txt','/home/andreak/src/Python/F1data/livetiming/livetiming20210314_125800.txt','/home/andreak/src/Python/F1data/livetiming/livetiming20210314_135800.txt','/home/andreak/src/Python/F1data/livetiming/livetiming20210314_145800.txt','/home/andreak/src/Python/F1data/livetiming/livetiming20210314_155800.txt','/home/andreak/src/Python/F1data/livetiming/livetiming20210314_165800.txt')
> session = fastf1.get_session(2021, 'testing', 3)
> session.load_laps(with_telemetry=True, livedata=livedata)

and I've got this error:

> Python 3.9.2 (default, Feb 20 2021, 18:40:11) 
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 7.19.0 -- An enhanced Interactive Python.
> 
> runfile('/home/andreak/src/Python/F1data/testGetDataFromLiveData.py', wdir='/home/andreak/src/Python/F1data')
> core        WARNING 	The Ergast API is not supported for testing
> core           INFO 	Loading Pre-Season Test - Practice 3
> api            INFO 	No cached data found. Downloading...
> data           INFO 	Loading live timing data. This may take a bit.
> api            INFO 	Parsing timing data...
> api         WARNING 	Driver  7: Ignoring late data for a previously processed lap.The data may contain errors (previous: 102; current 103)
> api            INFO 	Data has been written to cache!
> api            INFO 	No cached data found. Downloading...
> api            INFO 	Data has been written to cache!
> core           INFO 	Processing timing data...
> api            INFO 	No cached data found. Downloading...
> api            INFO 	Data has been written to cache!
> api            INFO 	No cached data found. Downloading...
> api            INFO 	Data has been written to cache!
> api            INFO 	No cached data found. Downloading...
> api            INFO 	Parsing car data...
> api         WARNING 	Driver  7: Car data is incomplete!
> api            INFO 	Data has been written to cache!
> api            INFO 	No cached data found. Downloading...
> api            INFO 	Parsing position data...
> Traceback (most recent call last):
> 
>   File "/home/andreak/src/Python/F1data/testGetDataFromLiveData.py", line 15, in <module>
>     session.load_laps(with_telemetry=True, livedata=livedata)
> 
>   File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/core.py", line 1238, in load_laps
>     self.load_telemetry(livedata=livedata)
> 
>   File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/core.py", line 1311, in load_telemetry
>     pos_data = api.position_data(self.api_path, livedata=livedata)
> 
>   File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/api.py", line 175, in cached_api_request
>     data = func(api_path, response=response, livedata=livedata)
> 
>   File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/api.py", line 837, in position_data
>     jrecord = parse(record[1], zipped=True)
> 
>   File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/api.py", line 1042, in parse
>     return parse(text.decode('utf-8-sig'))
> 
>   File "/home/andreak/.local/lib/python3.9/site-packages/fastf1/api.py", line 1037, in parse
>     return json.loads(text)
> 
>   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
> 
>   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> 
>   File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
>     obj, end = self.scan_once(s, idx)
> 
> JSONDecodeError: Expecting ':' delimiter

I can share the txt files with you if you need them to debug the above issue (when compressed in a tar.gz file, the txt data files occupy only 54MB of space)
 
Before the error these files have been created:

> -rw-r--r-- 1 andreak andreak 175884486 14 mar 17.51 car_data.ff1pkl
> -rw-r--r-- 1 andreak andreak       345 14 mar 17.50 session_status_data.ff1pkl
> -rw-r--r-- 1 andreak andreak    134700 14 mar 17.50 timing_app_data.ff1pkl
> -rw-r--r-- 1 andreak andreak    202430 14 mar 17.50 timing_data.ff1pkl
> -rw-r--r-- 1 andreak andreak       385 14 mar 17.50 track_status_data.ff1pkl

but I do not know if _car_data.ff1pkl_ is complete and _position_data.ff1pkl_ is completely missing.

**Comment by theOehrly** [comment] 2021-03-14 18:12
I can reproduce it. Working on a fix.
See also:
https://github.com/theOehrly/Fast-F1/issues/16#issuecomment-798952744

**Comment by theOehrly** [comment] 2021-03-14 18:57
Ok, please update and try again. It now works with my recorded data.

Please report in the other issue whether it works or not for better overview

**Comment by Xwang1976** [comment] 2021-03-19 20:38
> > Is it possible to run the command every hour?
> > I've understood that duplicated data are recognized and deleted. Does it happen even if more than two files contain the same data?
> 
> @Xwang1976 If you make the cron script, can you share it? Thanks

I've made the following scripts:
1) F1livetimingScheduler.sh

> #!/bin/bash
>  
> while true; do 
>     nohup $HOME/src/Python/F1data/F1livetiming.sh &
>     sleep 3600; 
> done

2) F1livetiming.sh

> #!/bin/bash
>  
>  _destinationFolder="$HOME/src/Python/F1data/livetiming/"
>  _fileName="livetiming"
>  _fileExt=".txt"
> 
> _now=$(date +"%Y%m%d_%H%M%S")
> 
> cd $_destinationFolder
> python -m fastf1.livetiming save --timeout 600 $_fileName$_now$_fileExt

They must be in $HOME/src/Python/F1data/ and $HOME/src/Python/F1data/livetiming/ must exist (or you have to change the paths accordingly).
When executing F1livetimingScheduler.sh, it calls an instance of F1livetiming.sh every hour and when you use ctrl+C to kill F1livetimingScheduler.sh, the existing instances will continue o run until they reach the 2 hours timeout or they do not receive any data for more than 10 minutes.

Fell free to use it at your own risk! I exclude all warranties :-)

**Comment by Xwang1976** [comment] 2021-03-26 16:37
Can anybody send me the .txt with the first 15 minutes of FP1?
I started too early and I do not have those data.
Thank you!

**Closed** 2021-04-10 12:50 UTC
