### ISSUE TITLE
Problem with Spanish FP2

### ISSUE THREAD

**Issue by TerminatorPlati** [theOehrly/Fast-F1#6] opened 2020-08-14 15:26 UTC
Hi, I am having problems with the FP2 of the Spanish GP. When trying to resample, the script crashes.

This is the error
`WARNING:root:Ergast lookup failed
INFO:root:Loading Spanish Grand Prix Practice 2
INFO:root:Getting summary...
INFO:root:Formatting summary...
INFO:root:Getting telemetry data...
INFO:root:Fetching car data
INFO:root:Parsing car data
INFO:root:Getting position data...
INFO:root:Fetching position
INFO:root:Parsing position
INFO:root:Resampling telemetry...
Traceback (most recent call last):
  File "main2piloti-2.py", line 22, in <module>
    giri = sess.load_laps()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\fastf1\utils.py", line 118, in decorator
    return func(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\fastf1\core.py", line 340, in load_laps
    telemetry, lap_start_date = self._load_telemetry()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\fastf1\core.py", line 448, in _load_telemetry
    self._augment_position()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\fastf1\core.py", line 600, in _augment_position
    driver_ahead = self._make_trajectory(lap)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\fastf1\core.py", line 719, in _make_trajectory
    dmap[:, index] = fix_suzuka(projection_index.copy(), reference_s)
ValueError: could not broadcast input array from shape (33114) into shape (64013)
`

**Comment by theOehrly** [comment] 2020-08-14 21:30
The problem is caused by Williams changing their drivers mid session (developement driver to Russel). Therefore only about half of the session is available for Russel and that's why the array size doesn't match. I'll see how this can be fixed.
This problem occurs when calculating the "DistanceToDriverAhead" column.

A very crude fix is to go into core.py and replace line 446 like this:
```
# can_find_reference = position != {}
can_find_reference = False
```
This will disable the calculation of the "DistanceToDriverAhead" completely.
You'll still get some warnings though because of the missing data, but I think at least the data for other drivers should be fine.

**Comment by TerminatorPlati** [comment] 2020-08-15 11:44
Ok, thanks.

Edit:
I report that the FP3 data of the GP of Spain are wrong. I do not know if it is the script or the F1 data

**Comment by theOehrly** [comment] 2020-08-15 12:42
FP2 should be fixed as good as possible. I think Williams' reserve driver wasn't even driving in that session but only in FP1. There is timing data for RUS for the whole session. But position and car data changes from Aitkin to Russel mid-session. You will get a warning about this now. The two datasets are not merged. That would just be too much effort to do. Car and position data will simply be missing for Russel for the first part of the session. 

About FP3, do you mean the car data (Speed, RPM, ...)? Or is there more stuff that's wrong?
There's nothing I can really do about the car data. The api is returning data for all these drivers: `['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '33', '44', '55', '63', '77', '99']`
Last time I checked, there were only 20 drivers, not 36.... Something is messed up there by F1(again)
Someone would need to manually puzzle together which data actually goes were.

**Comment by TerminatorPlati** [comment] 2020-08-15 13:53
yes, by FP3 I mean the car data. doing the plot are staggered and do not absolutely respect the track.

**Comment by theOehrly** [comment] 2020-08-15 14:08
Do you maybe have a short code example of what you are trying to plot?

**Comment by TerminatorPlati** [comment] 2020-08-15 15:32
`
import fastf1 as ff1
from fastf1 import plotting
from matplotlib import pyplot as plt

anno = 2020
gp = 'Spanish Grand Prix'
sessione = 'FP3'

sess = ff1.get_session(anno, gp, sessione)

giri = sess.load_laps()

fastPilota1 = giri.pick_driver('LEC').pick_fastest()
fastPilota2 = giri.pick_driver('VET').pick_fastest()

Pilota1Space = fastPilota1.telemetry['Space']
Pilota1Y = fastPilota1.telemetry['Speed']

Pilota2Space = fastPilota2.telemetry['Space']
Pilota2Y = fastPilota2.telemetry['Speed']

fig, ax = plt.subplots()

ax.plot(Pilota1Space, Pilota1Y, color='RED')
ax.plot(Pilota2Space, Pilota2Y, color='YELLOW')

plt.show()
`

**Comment by theOehrly** [comment] 2020-08-27 21:58
This should be fixed now and hopefully also for upcoming events

**Closed** 2020-09-11 19:40 UTC
