### ISSUE TITLE
[BUG] Wrong positions during race (possibly caused by red flag)

### ISSUE THREAD

**Issue by pesaventofilippo** [theOehrly/Fast-F1#440] opened 2023-08-27 17:34 UTC
### Describe the issue:

If you load the recent 2023 Dutch GP Race (before data is available on Ergast), the `Position` values for at least the last lap are incorrect.
For example, for the last lap (72), the drivers in the top 4 are VER, PER, GAS and ALO, which is not correct.
It's normal to have PER in the wrong position because he had a penalty applied after the race, but even then, on-track PER finished behind ALO, and GAS behind ALO and PER.

What I suspect is the bug is caused by the red flag and the timing: if you look at the `Time` column (from the docs: the session time at which the lap ended), then for some reason VER finishes first, then PER, then GAS and then ALO (the same "incorrect" order as before). Maybe the timings got out of order when the drivers exited the pit lane for the restart?

Here's a snippet of the data for the last lap and the top 4 drivers:
<img width="271" alt="Screenshot 2023-08-27 alle 19 27 31" src="https://github.com/theOehrly/Fast-F1/assets/32228386/de5a613a-5c80-4ec2-80f2-2810d7a5f724">

### Reproduce the code example:

```python
import fastf1
session = fastf1.get_session(2023, "Zandvoort", "R")
session.load()
lap_72 = session.laps[session.laps.LapNumber == 72]  ## Position data is wrong
```

**Comment by theOehrly** [comment] 2023-08-28 11:55
I'll take a look at it, hopefully later today. I probably need to review that in comparison with F1TV onboard footage. I'm currently still travelling and can't do that at the moment.

**Comment by theOehrly** [comment] 2023-08-28 18:07
Note for documentation: the issue was unrelated to the red flag. Instead, it was caused by incorrect lap alignment because of drivers pitting on the first few laps. This is resolved by using a lap with no drivers pitting for lap alignment.

**Closed** 2023-08-28 21:39 UTC
Labels: bug
